name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build
        run: chmod +x gradlew && ./gradlew build
      - uses: actions/upload-artifact@v3
        if: github.event_name == 'workflow_dispatch'
        with:
          name: Compiled-files
          path: build/libs/*.jar

        
